### ISSUE TITLE
throw Type error in every pages

### ISSUE THREAD

**Issue by llemllen** [tavyandy97/span-tree#96]
I have been using it normally. About a few months ago, every page I opened would throw an error. Whether it was GitLab or not, I have tried to disable all other extensions and only enable SpanTree, but the problem still exists

![image](https://github.com/user-attachments/assets/b8917db0-c8bc-4b94-b216-ce6d666e9e4c)

```js
content.js:2 Uncaught TypeError: p is not a function
    at 3955 (content.js:2:57857)
    at t (content.js:2:325739)
    at content.js:2:326583
    at content.js:2:326592
```

![image](https://github.com/user-attachments/assets/91ce7923-258d-42c4-bac1-59d48e36709d)

![image](https://github.com/user-attachments/assets/6a516081-0ebd-4732-82e7-dd12a455a18d)

**Comment by justforuse** [comment]
Same here
